name: Add issues to the roadmap project

on:
  issues:
    types:
      - labeled

jobs:
  add-issue-to-roadmap-project:
    name: Add issue to the roadmap project
    runs-on: ubuntu-latest
    steps:
      # 'kind/feature' AND 'priority/backlog' labels -> 'Backlog' column
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/add-to-project@2e5cc851ca7162e9eb510e6da6a5c64022e606a7 # v1.0.0
        with:
          project-url: https://github.com/orgs/aquasecurity/projects/25
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          labeled: kind/feature, priority/backlog
          label-operator: AND
        id: add-backlog-issue
      - uses: titoportas/update-project-fields@421a54430b3cdc9eefd8f14f9ce0142ab7678751 # v0.1.0
        if: ${{ steps.add-backlog-issue.outputs.itemId }}
        with:
          project-url: https://github.com/orgs/aquasecurity/projects/25
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          item-id: ${{ steps.add-backlog-issue.outputs.itemId }} # Use the item-id output of the previous step
          field-keys: Priority
          field-values: Backlog

      # 'kind/feature' AND 'priority/important-longterm' labels -> 'Important (long-term)' column
      - uses: actions/add-to-project@2e5cc851ca7162e9eb510e6da6a5c64022e606a7 # v1.0.0
        with:
          project-url: https://github.com/orgs/aquasecurity/projects/25
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          labeled: kind/feature, priority/important-longterm
          label-operator: AND
        id: add-longterm-issue
      - uses: titoportas/update-project-fields@421a54430b3cdc9eefd8f14f9ce0142ab7678751 # v0.1.0
        if: ${{ steps.add-longterm-issue.outputs.itemId }}
        with:
          project-url: https://github.com/orgs/aquasecurity/projects/25
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          item-id: ${{ steps.add-longterm-issue.outputs.itemId }} # Use the item-id output of the previous step
          field-keys: Priority
          field-values: Important (long-term)

      # 'kind/feature' AND 'priority/important-soon' labels -> 'Important (soon)' column
      - uses: actions/add-to-project@2e5cc851ca7162e9eb510e6da6a5c64022e606a7 # v1.0.0
        with:
          project-url: https://github.com/orgs/aquasecurity/projects/25
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          labeled: kind/feature, priority/important-soon
          label-operator: AND
        id: add-soon-issue
      - uses: titoportas/update-project-fields@421a54430b3cdc9eefd8f14f9ce0142ab7678751 # v0.1.0
        if: ${{ steps.add-soon-issue.outputs.itemId }}
        with:
          project-url: https://github.com/orgs/aquasecurity/projects/25
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          item-id: ${{ steps.add-soon-issue.outputs.itemId }} # Use the item-id output of the previous step
          field-keys: Priority
          field-values: Important (soon)

      # 'kind/feature' AND 'priority/critical-urgent' labels -> 'Urgent' column
      - uses: actions/add-to-project@2e5cc851ca7162e9eb510e6da6a5c64022e606a7 # v1.0.0
        with:
          project-url: https://github.com/orgs/aquasecurity/projects/25
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          labeled: kind/feature, priority/critical-urgent
          label-operator: AND
        id: add-urgent-issue
      - uses: titoportas/update-project-fields@421a54430b3cdc9eefd8f14f9ce0142ab7678751 # v0.1.0
        if: ${{ steps.add-urgent-issue.outputs.itemId }}
        with:
          project-url: https://github.com/orgs/aquasecurity/projects/25
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          item-id: ${{ steps.add-urgent-issue.outputs.itemId }} # Use the item-id output of the previous step
          field-keys: Priority
          field-values: Urgent